#!/bin/bash
# OTB's script

#awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | column -t -s $'\t'  | rofi -dmenu -i -no-show-icons -width 1000

awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/leftwm/Mod-Key-Bindings-List-Cheat-sheet-LeftWm.txt | column -t -s $'\t'  | rofi -dmenu -i -no-show-icons -width 1000
