#!/bin/sh
# depends on fontawesome
user="${USER}@"
hostname="${HOSTNAME:-${hostname:-$(hostname)}}"
host="$(cat /sys/devices/virtual/dmi/id/product_name)"
OS="$(cat /etc/os-release | grep PRETTY_NAME | sed 's/PRETTY_NAME=//g'| sed 's/"//g')"
gtktheme="$(grep gtk-theme-name ~/.config/gtk-3.0/settings.ini | sed 's/gtk-theme-name=//')"
icontheme="$(grep gtk-icon ~/.config/gtk-3.0/settings.ini | sed 's/gtk-icon-theme-name=//')"
termfont="$(gsettings get org.gnome.desktop.interface monospace-font-name | sed "s/'//g" | awk '{print $1}')"
resolution="$(xrandr | grep \* | sed 's/59.95\*+//g')"
#Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Packages="$(dpkg -l | grep -c ^i)"
Shell="$(basename "$SHELL")"
CPU="$(lscpu | grep Model\ name | awk '{print $4" "$5" "$6}')" 
GPU="$(lspci | grep VGA | sed 's/[][]//g' | awk '{print $12" "$13" "$18" "$19}')"
RAM="$(free -h | grep Mem: | awk '{print $3 "/" $2}')"
IP="$(hostname -I | awk '{print $1}')"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='Desktop'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='Desktop'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'

fi

# COLORS
c1="\e[91m" # Red
c2="\e[32m" # Light Green
c3="\e[33m" # Yellow
c4="\e[34m" # Calm Blue
c5="\e[35m" # Violet
c6="\e[36m" # Arch Blue
c7="\e[37m" # White
c8="\e[96m" # Cyan Blue 
c9="\e[39m" # Light Grey
c10="\e[40m" # Dark Grey
c11="\e[95m" # Light Purple
c12="\e[94m" # Light Blue
c20="\e[0m" # Normal

# An Error echo Wrapper
err0r()
{
	echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)"
	echo ""
	exit 86
}


# A Warning echo wrapper
warn ()
{
	echo >&2 "$(tput bold; tput setaf 3)[!] WARNING: ${*}$)tput sgr0)"
	echo ""
}



# A Message echo Wrapper
msg ()
{
	echo "$(tput bold; tput setaf 2)[+] ${*}$(tput sgr0)"
}



echo  ""
echo -e ${c1}'          _,met$$$$$gg.        '   ${c20} ${c6}$user${c20}$hostname
echo -e ${c1}'       ,g$$$$$$$$$$$$$$$P.     '   ${c20}----------- 
echo -e ${c1}'     ,g$$P""       """Y$$.".   '   ${c6}OS  :  ${c20}$OS 			 
echo -e ${c1}'    ,$$P"              `$$$."  '   ${c6}Host  :  ${c20}$host 
echo -e ${c1}'   ,$$P       ,ggs.     `$$b:  '   ${c6}Kernel  :  ${c20}$Kernel 
echo -e ${c1}'  `d$$"     ,$P""   .    $$$   '   ${c6}Uptime  :  ${c20}$Uptime          
echo -e ${c1}'   $$P      d$"     ,    $$P   '   ${c6}Packages  :  ${c20}$Packages         
echo -e ${c1}'   $$:      $$.   -    ,d$$"   '   ${c6}Shell  :  ${c20}$Shell 
echo -e ${c1}'   $$\;      Y$b._   _,d$P     '   ${c6}Resolution  :  ${c20}$resolution
echo -e ${c1}'   Y$$.    `.`"Y$$$$P""        '   ${c6}GTK Theme  :  ${c20}$gtktheme
echo -e ${c1}'   `$$b      "-.__             '   ${c6}Icon Theme  :  ${c20}$icontheme
echo -e ${c1}'    `Y$$                       '   ${c6}Terminal  :  ${c20}$TERM
echo -e ${c1}'     `Y$$.                     '   ${c6}Terminal Font  :  ${c20}$termfont
echo -e ${c1}'       `$$b.                   '   ${c6}CPU  :  ${c20}$CPU
echo -e ${c1}'         `Y$$b.                '   ${c6}GPU  :  ${c20}$GPU
echo -e ${c1}'            `"Y$b._            '   ${c6}RAM  :  ${c20}$RAM
echo -e ${c1}'                `""""          '   ${c6}IP  :   ${c20}$IP 
echo ""
