#!/bin/bash

# Xbt-Deb-v3 -- External Backup Tool (v. 3.1) Ported By Bruce E. Scott
#                                                       11/202020
# Xbt-Deb-v3 -- External Backup Tool (v. 3.1) is also known as
# XBT -- External Backup Tool (v. 3.1) -- by Joe Collins. (www.ezeelinux.com)
# ...Special Thanks to Jeremy O'Connell and Jody James. (February 18th, 2017)
# (GNU/General Public License version 2.0)
#
# Use For Debian 9 and up, Ubuntu 16.04 and up and Linux Mint 18.x and up.
#
# A Script to create a snapshot backup of /etc and /home on a dedicated
# external USB drive.
#
##*****************************************************************************
# Date: 5/21/2019
# Hello,
# I ported Joe's great XBT backup tool so that it will work
# on Solus Budgie 4.0 and the EOPKG package manager.
#
# This tool still in accordance with (GNU/General Public License version 2.0)
# and all changes were made by me(Bruce E. Scott) on 5/12/2019...
#
# This should work with any Distro that uses the EOPKG manager!
# It has been tested on Solus 4.0 "Fortitude" ONLY and works so far!!
#
# Note: when launching XBT there is a 6 seconds delay while EOPKG checks for
# Less, Parted, Rsync to see if there installed. If not, they will be
# installed and you will be asked for your Sudo password to install them!
#
# Use this adapted Solus software at your own RISK!!! You have been warned!
##*****************************************************************************
# Date:  6/5/19		"Cya, Copyright (c) 2017, Jeremy O'Connell"
# I added Jeremy O'Connell "CYA Backup Solution" to the Function & Menu areas
# so that it can be ran from inside XBT-Solus & XBT-MJ (For Manjaro Arch).
# The command line function for CYA is set to "CYA Save"... Any other commands
# options will need to be done from a "Terminal Command Line"
#
# I add this to make the backup processes easier to do from one "Menu"
# Bruce E. Scott...
##*****************************************************************************
# Date: 07/03/19
# I changed the package manager commands to work with Manjaro Arch.
# The Path's are the same for Solus and Manjaro Arch: 07/03/19 -Bruce
#
# Note: when launching XBT there maybe a 6 seconds delay while PACMAN checks for
# Udate to the system and Repo's then check for Less, Parted, Rsync to see if there
# installed. If not, they will be downloaded installed automatically and you will be
# asked for your Sudo password to install them and Prompt you for [y/n]!
#
# Use this NOW adapted Manjaro Arch software at your own RISK!!! You have been warned!
##*****************************************************************************
# Date: 11/27/19
# Updated to work for Manjaro Arch /Arch OS's $HOSTNAME on 11/27/19
# Updated The Rsync Command will exclude some Directories That are not needed... -Bruce
#
# sudo rsync -aAHXv --delete --progress --exclude=/tmp/* --exclude=**/*tmp*/
# --exclude=/run/** --exclude=/mnt/** --exclude=/media/*/** --exclude=swapfile
# --exclude=**/lost+found*/ --exclude=/bruce/.cache/ --exclude=**/*cache*/
# --exclude=**/*Cache*/ --exclude=/var/run/** --exclude=**/*Trash*/ --exclude=**/*trash*/
# --exclude=/bruce/Music/ServerMusic/** --exclude=/bruce/Videos/** --exclude=/cya/**
##*************************************************************
# I updated this script to now work on Manjaro Arch and the PACMAN package manager
# on 07/03/19 -Bruce
##*************************************************************
# Date:  01/18/2020 (V. 3.1) Update ---- Bruce E. Scott
# I updated V3.0 to work for Debian OS's with the APT Package Manager.
# I updated this script to now work with differant switches and
# "excluding" items. They are:
#     sudo rsync -aAHXv --delete --progress --exclude=/tmp/*
#    --exclude=**/*tmp*/ --exclude=/run/** --exclude=/mnt/**
#    --exclude=/media/*/** --exclude=swapfile --exclude=**/lost+found*/
#    --exclude=/bruce/.cache/ --exclude=**/*cache*/
#    --exclude=**/*Cache*/ --exclude=/var/run/** --exclude=**/*Trash*/
#    --exclude=**/*trash*/ --exclude=/bruce/Music/ServerMusic/**
#    --exclude=/bruce/Documents/Master-Docs/** --exclude=/timeshift/**
#    --exclude=/bruce/Videos/** --exclude=/cya/**
# to keep them from being back-up to the XBT drive. They do not need to
# be back-uped. This is done on the server...
# Also a verson update to V 3.1... 01/18/2020
##*****************************************************************************
# Date:  11/20/2020 (V. 3.1) Update ---- Bruce E. Scott
# I made some changes to this Version of xbt-Deb-v3 -- External Backup Tool (v. 3.1)
# to include the VM directory from being backed up by adding ,
# --exclude=/bruce/VirtualBox-VMs/** to the /home/ section of the Backup script.
# Also chanced the script name to xbt-Deb-v3
##*****************************************************************************
##*****************************************************************************
# ...And away we go!

# Declare static variables:
user=$USER

host=$HOSTNAME

# Here we update the packages and Repo Information: 07/03/19 -Bruce
echo "    Starting full system update $USER..."
 sudo apt update
 sudo apt dist-upgrade
# -yy

# Check for rsync, less and parted, install if needed:

dpkg -l | grep -qw less || sudo apt-get install -yyq less
dpkg -l | grep -qw parted || sudo apt-get install -yyq parted
dpkg -l | grep -qw rsync || sudo apt-get install -yyq rsync

# Set functions:

cya() {
# Cya, Copyright (c) 2017, Jeremy O'Connell
# System Backup Utility...
# The "cya_s" is a small script kept in the "~/bin" to
# pass the "cya save" terminal command so that
# this menu will work. Other wise use the Terminal for
# other options....
clear
cya_s
clear
 greeting
}

# Set functions:

before() {
# umounting mounted drives in the fstab before backup
# for Vm-Data and the ServerMusic network drive.
clear
sudo umount /vm-data /vm-data-1 /home/bruce/Music/ServerMusic /home/bruce/Documents/Master-Docs
clear
 greeting
}

after() {
# Remounting all drives in the fstab after backup!
clear
sudo mount -a
clear
 greeting
}


backup() {

# XBT backup. Runs full backup of /etc and /home directories on host machine.

# Checking for valid media:

if [ ! -d /media/$user/XBT_Drive ]; then

    clear
    echo $'\n'$"XBT Backup"
    echo "XBT Error: NO XBT DRIVE FOUND! Please make sure XBT_Drive USB is connected."
	echo "If you just set up the XBT Drive, remove it and plug it back in."
    greeting

fi

# Checking for sudo permissions:

sudo ls > /dev/null

# Making sure user has ownership of the XBT Drive:

sudo chown $user /media/${user}/XBT_Drive/

# Generate XBT log file file if not there already:

if [ ! -f /media/$user/XBT_Drive/XBT_Backups/xbt-backup.log ]; then
    echo "XBT -- External Backup Tool - Log File" \
    > /media/$user/XBT_Drive/XBT_Backups/xbt-backup.log6
fi

# Log file is created in /tmp:

date_and_time="$(date)"
echo $'\n'$"Backup sent to XBT_Drive USB from $host by user '$user' on" \
> /tmp/backup.log
echo "$date_and_time. Any errors?" >> /tmp/backup.log

# Begin backup operations using rsync:

# Creating machine specific directories:

mkdir -p /media/$user/XBT_Drive/XBT_Backups/$host

# Starting synchronization:

clear
echo $'\n'$"XBT Backup"
echo $'\n'$"Backing up /etc..."
    sudo rsync -aAHXv --delete --progress --exclude=/tmp/* \
--exclude=**/*tmp*/ --exclude=/run/** --exclude=/mnt/** --exclude=/media/*/** \
--exclude=swapfile --exclude=**/lost+found*/ --exclude=/bruce/.cache/ \
--exclude=**/*cache*/ --exclude=**/*Cache*/ --exclude=/var/run/** \
--exclude=**/*Trash*/ --exclude=**/*trash*/ --exclude=/bruce/Music/ServerMusic/** \
--exclude=/bruce/Documents/Master-Docs/** --exclude=/bruce/Videos/** \
--exclude=/timeshift/** --exclude=/cya/** /etc/ \
    /media/$user/XBT_Drive/XBT_Backups/$host/Etc_Backup/ 2>> /tmp/backup.log

# Checking status of rsync exit code:

if [ "$?" != "0" ]; then
    echo "Starting second pass for /etc..." | tee -a /tmp/backup.log
    sudo rsync -aAHXv --delete --progress --exclude=/tmp/* \
--exclude=**/*tmp*/ --exclude=/run/** --exclude=/mnt/** --exclude=/media/*/** \
--exclude=swapfile --exclude=**/lost+found*/ --exclude=/bruce/.cache/ \
--exclude=**/*cache*/ --exclude=**/*Cache*/ --exclude=/var/run/** \
--exclude=**/*Trash*/ --exclude=**/*trash*/ --exclude=/bruce/Music/ServerMusic/** \
--exclude=/bruce/Documents/Master-Docs/** --exclude=/bruce/Videos/** \
--exclude=/timeshift/** --exclude=/cya/** /etc/ \
    /media/$user/XBT_Drive/XBT_Backups/$host/Etc_Backup/ 2>> /tmp/backup.log
    if [ "$?" != "0" ]; then
        echo "...Second pass had some errors errors. Moving on to /home anyway." \
        | tee -a /tmp/backup.log
        # Set error flag for log file completion:
        local etc_error_code=yes
    fi
fi

echo $'\n'$"Backing up /home..."
    sudo rsync -aAHXv --delete --progress --exclude=/tmp/* \
--exclude=**/*tmp*/ --exclude=/run/** --exclude=/mnt/** --exclude=/media/*/** \
--exclude=swapfile --exclude=**/lost+found*/ --exclude=/bruce/.cache/ \
--exclude=**/*cache*/ --exclude=**/*Cache*/ --exclude=/var/run/** \
--exclude=**/*Trash*/ --exclude=**/*trash*/ --exclude=/bruce/Music/ServerMusic/** \
--exclude=/bruce/Documents/Master-Docs/** --exclude=/bruce/Videos/** \
--exclude=/timeshift/** --exclude=/cya/** --exclude=/bruce/VirtualBox-VMs/** \
 /home/ \
  /media/$user/XBT_Drive/XBT_Backups/$host/Home_Backup/ 2>> /tmp/backup.log

# Checking status of rsync exit code:

if [ "$?" != "0" ]; then
    echo "Starting second pass for /home..." | tee -a /tmp/backup.log
    sudo rsync -aAHXv --delete --progress --exclude=/tmp/* \
--exclude=**/*tmp*/ --exclude=/run/** --exclude=/mnt/** --exclude=/media/*/** \
--exclude=swapfile --exclude=**/lost+found*/ --exclude=/bruce/.cache/ \
--exclude=**/*cache*/ --exclude=**/*Cache*/ --exclude=/var/run/** \
--exclude=**/*Trash*/ --exclude=**/*trash*/ --exclude=/bruce/Music/ServerMusic/** \
--exclude=/bruce/Documents/Master-Docs/** --exclude=/bruce/Videos/** \
--exclude=/timeshift/** --exclude=/cya/** --exclude=/bruce/VirtualBox-VMs/** \
 /home/ \
    /media/$user/XBT_Drive/XBT_Backups/$host/Home_Backup/ 2>> /tmp/backup.log
fi

if [ "$?" == "0" ]; then

    # Clear any accidental input during backup:

    read -t 1 -n 10000 discard

    # Get the time:

    time="$(date +"%T")"

    clear

    # Report errors with /etc backup if there were any:

    if  [ "$etc_error_code" == "yes" ]; then
        echo "XBT Backup: /home backup successful! Some errors with /etc" \
        >> /tmp/backup.log
        echo "Please review XBT Log to see them."
    else
        echo "No errors! :)" >> /tmp/backup.log
    fi

    echo "XBT Backup: Successfully completed at $time!" | tee -a /tmp/backup.log

    # Log file is created or appended on XBT_Drive from /tmp:
    # (backup.log will be removed from /tmp on next reboot.)

    cat /tmp/backup.log >> /media/$user/XBT_Drive/XBT_Backups/xbt-backup.log

else

    # Alert user there were some errors and return to Main Menu:

    # Clear any accidental input during backup:

    read -t 1 -n 10000 discard

    # Get the time:

    time="$(date +"%T")"

    clear

    # Report errors with /etc backup if there were any:

    if  [ "$etc_error_code" = "yes" ]; then
        echo "XBT Backup: There were some errors with /etc backup!"
        echo "Please review XBT Log to see them."
    fi

    echo "XBT Backup: Backup of /home had errors after two passes at $time!" \
    | tee -a /tmp/backup.log
    echo "Please review XBT Log to see them."
    cat /tmp/backup.log >> /media/$user/XBT_Drive/XBT_Backups/xbt-backup.log
    echo "Wait! Syncing drives..."
    sync
    echo "...Done."
    greeting

fi

# Writing all cached data to drives and returning to Main Menu:

echo $'\n'$"Wait! Syncing drives..."
sync
echo "..Done."
echo "It's now safe to remove XBT_Drive."

# Exit if running from command line:

if [ "$mode" == "CLI" ]; then
	echo "Exiting XBT.. Goodbye $USER!"
	exit
fi

greeting

}

restore() {

# XBT Restore. Runs an rsync operation to restore host's /home directory.

# Checking for valid media:

if [ ! -d /media/$user/XBT_Drive ]; then

    clear
	echo $'\n'$"XBT Restore"
    echo "XBT Error: NO XBT DRIVE FOUND! Please make sure XBT_Drive USB is connected."
    greeting

fi

# Checking for sudo permissions

sudo ls > /dev/null

# Starting restore function and offering user a chance to exit:

clear
echo $'\n'$"XBT Restore"

# Check for valid media and the host's backup directory:

if [ ! -d /media/$user/XBT_Drive/XBT_Backups/$host/ ]; then

    echo "XBT Error: Cannot find valid backup directory for $host!"
    echo "Drive may not have been used to backup this machine or the"
    echo "XBT_Backups/$host directory may have been moved or deleted."
    greeting

fi

echo $'\n'$"WARNING!"$
echo $'\n'$"Any new files created in /home since last backup WILL BE DELETED!"
echo "Are you sure you want to restore now? [y/N]"
read -n 1 -s choice

    if test "$choice" == "y"; then

        # Giving user a chance to close other apps and starting rsync.

        echo "Close any running applications and press any key to continue."
        read -n 1 -s
        echo $'\n'$"Restoring /home... Please DO NOT open any applications."
        sudo rsync -aAHXv --delete --progress --exclude=/tmp/* \
--exclude=**/*tmp*/ --exclude=/run/** --exclude=/mnt/** --exclude=/media/*/** \
--exclude=swapfile --exclude=**/lost+found*/ --exclude=/bruce/.cache/ \
--exclude=**/*cache*/ --exclude=**/*Cache*/ --exclude=/var/run/** \
--exclude=**/*Trash*/ --exclude=**/*trash*/ --exclude=/bruce/Music/ServerMusic/** \
--exclude=/bruce/Documents/Master-Docs/** --exclude=/bruce/Videos/** \
--exclude=/timeshift/** --exclude=/cya/** \
        /media/$user/XBT_Drive/XBT_Backups/$host/Home_Backup/ /home/ \

            # Checking status of rsync exit code:

            if [ "$?" == "0" ]; then

                # Prompt user to restart machine and exit:

                # Clear any accidental input during restore:

                read -t 1 -n 10000 discard

                echo $'\n'$"Restoration complete!"
                echo "Wait! Syncing drives..."
                sync
                echo "...Done."
                echo "It's now safe to remove XBT_Drive."
                echo "Restart machine for all changes to take effect."
                echo $'\n'$"Press any key to exit XBT."
                read -n 1 -s
                clear
                echo "Exiting XBT ..Goodbye!"
                sleep 2
                tput cnorm
                exit

            else

                # Returning to Main Menu if rsync fails:

                # Clear any accidental input during restore:

                read -t 1 -n 10000 discard

                clear
                echo $'\n'$"XBT Restore"
                echo "XBT Error: rsync exited with errors!"
                echo "DO NOT EXIT XBT UNTIL YOU:"
                echo $'\n'$"    Make sure XBT Drive USB is still plugged in."
                echo "    Remount XBT Drive USB by unplugging it and plugging it back in."
                echo $'\n'$"Wait a few seconds and try running XBT Restore again."
                echo "You may need to manually restore your data if errors persist."
                greeting

            fi

    else

        clear
        echo "XBT restoration canceled."
        greeting

    fi

# Exit if running from command line:

if [ "$mode" == "CLI" ]; then
	exit
fi

clear
greeting

}

setup_drive() {

# XBT Drive Setup: This function will format and label an USB drive for XBT.


# Checking for any USB drive:

if [[ ! $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]]; then

    # Show error and exit to Main Menu:

    clear
    echo $'\n'$"XBT Drive Setup"
    echo "XBT Error: No valid USB drives to setup! Please plug one in."
    greeting

fi

# Show user warnings:

clear
cat << _EOF_

XBT Drive Setup

 You must create an XBT Drive before you can use XBT.

 You can use any USB storage device for your XBT Drive. It should have enough
 storage capacity to hold all of the data in the /home directories of all the
 machines you'd like to make backups from. This tool works with USB storage
 devices with under 2 TB of total data capacity. Lager drives will have to be
 formatted manually. XBT Drive Setup will format and label a drive for use with
 XBT. The partition will be labeled "XBT_Drive" so the program can find it.
 The drive MUST be formatted with a native Linux file system such as Ext4
 or XFS for the backups to retain the correct permissions. You must run XBT
 Backup to set the correct ownership permissions for you new XBT Drive.


  *************************************************************************
  * WARNING: XBT-Debian Drive Setup will clear ALL DATA on the USB drive chosen! *
  *************************************************************************

 Double check you have the drive you want to use plugged in before continuing!

_EOF_

# Giving the user a chance to opt out:

echo "Would you like to setup your XBT Drive now? [y/N]"
read -n 1 -s choice

if test "$choice" == "y"; then

    # Checking for sudo permissions:

    sudo ls >> /dev/null

    # Getting list of drives:

    lsblk -p -S -o  NAME,TRAN,SIZE | grep usb > /tmp/xbt-usb-list.tmp

    # Letting user select the disk:

    echo "Type the number for the USB Drive you'd like to use and press Enter."
    echo "You can also just press Enter if there is only one USB drive listed."
    num=1
        while read p; do
      	echo $num "-" $p
    	num=$(($num + 1))
    done </tmp/xbt-usb-list.tmp

    # Reading user's choice:

    read line

    # Assigning choice to a variable and fixing the format of the answer:

    chosen_disk=` sed -n "$line p" /tmp/xbt-usb-list.tmp | awk '{print $1}' `

    sudo rm /tmp/xbt-usb-list.tmp

    # Checking if user's choice variable is empty before continuing:

    if  [ -z "$chosen_disk" ]; then

        echo "XBT Error: No valid USB drive chosen. Try again."
        sleep 3
        setup_drive

    fi

    clear

    # Last Chance! Asking user if they want to format the chosen disk:

    echo $'\n'$"Are you sure you want to use $chosen_disk for the XBT Drive??"
    echo "WARNING!! This will delete ALL DATA already on the drive!"
    echo $'\n'$"Type in 'YES' in all caps and press Enter to continue."
    echo "Press Enter to abort and return to XBT Main Menu."

    # Reading answer about formatting:

    read format

    # if chosen, deleting data on drive and creating new formatted partition:

    if test "$format" == "YES"; then

        # Format the chosen USB drive:

	    echo "Formatting ${chosen_disk}. Please wait..."

        # Un-mounting the drive:

        sudo umount ${chosen_disk}1 >/dev/null 2>&1

        # Write 2 GB's of zeros to clear old partition tables:

	    sudo dd if=/dev/zero of=${chosen_disk} bs=1024k count=2048

	    # Creating new label and partition:

	    sudo parted --script ${chosen_disk} mklabel msdos mkpart primary ext4 1MiB 100%

	    # Creating new ext3 file system:

	    sudo mkfs.ext4 -F ${chosen_disk}1
	    echo "${chosen_disk} has been formatted! Adding label..."

        # Labeling the drive "XBT_Drive":

        sudo e2label ${chosen_disk}1 "XBT_Drive"
        sync

        # Returning to Main Menu:

        # Clear any accidental input during restore:

        read -t 1 -n 10000 discard

        clear
        echo $'\n'$"XBT Drive Setup complete!"
        echo $'\n'$"You should now remove the USB dive and plug it back in to"
        echo "make sure that it is property recognized by the system."
        echo "You can then run your first XBT Backup."
        greeting

    else

        # Abort format and return to Main Menu:

	    echo "XBT Drive Setup canceled. ${chosen_disk} not formatted."; sleep 3
        clear
        greeting

    fi

else

    # Abort XBT Drive Setup and return to Main Menu:

    clear
    greeting

fi

greeting

}

greeting() {

# XBT Main Menu.

	cat << _EOF_
 ******************************************************************
 * <:Excluded Items; You can edited this in the XBT-Deb-v3 File:> *
 ******************************************************************
    sudo rsync -aAHXv --delete --progress --exclude=/tmp/*
    --exclude=**/*tmp*/ --exclude=/run/** --exclude=/mnt/**
    --exclude=/media/*/** --exclude=swapfile --exclude=**/lost+found*/
    --exclude=/bruce/.cache/ --exclude=**/*cache*/
    --exclude=**/*Cache*/ --exclude=/var/run/** --exclude=**/*Trash*/
    --exclude=**/*trash*/ --exclude=/bruce/Music/ServerMusic/**
    --exclude=/bruce/Documents/Master-Docs/** --exclude=/timeshift/**
    --exclude=/bruce/Videos/** --exclude=/cya/** /home/
 *************************************************************

    XBT-Debian Addition -- External Backup Tool (Version 3.1)
  Updated to work for Debian OS's $HOSTNAME on 01/17/2020

           Welcome To XBT Backup $USER!
       Main Menu: What would you like to do?
 *************************************************************
 *         ***>>--Warning $USER---<<***                      *
 *        Unmount ServerMusic Partitions/Mounts              *
 *  before backups. You will have to enter Your PASSWORD!!!  *
 *************************************************************

 Press the number of your choice $USER:
    1 - Backup.
    2 - Restore.
    3 - Setup XBT Drive.
    4 - Get some help.
    5 - View backup log. ('q' exits.}
    6 - Refresh USB Status.
    7 - *Unmount drives before backup.
    8 - *Remount drives after backup.
    9 - *Cya System BackUp Utility. (*"Not User Home"*)
        {Set to "Save" backup. Otherwise Use The Terminal CL.}
    0 - Exit XBT.
_EOF_

# Confirming that XBT_Drive USB is ready:

if [ ! -d /media/$user/XBT_Drive ]; then

    # Alert user that XBT Drive is not found:

    echo $'\n'$"USB Status: NO XBT DRIVE FOUND! Please make sure XBT_Drive USB is connected."
    if [[ $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]]; then

        # Alert user that drives are connected but no XBT Drive:

        echo "            USB drive(s) connected. Plug in XBT Drive or setup a new one now."

    fi

else

    # Alert user that XBT Drive is ready for action:

    echo $'\n'$"USB Status: XBT Drive is ready!"

fi


# Hide the cursor.

tput civis

# Wait for user to make a choice and run chosen functions:

read -n 1 -s choice;
	case $choice in
	    1) backup;;
	    2) restore;;
	    3) setup_drive;;
	    4) help;;
            5) log;;
            6) clear;echo $'\n'$"Refreshing USB Status...";sleep 2;clear;greeting;;
            7) before;;
            8) after;;
	    9) cya;;
            0) clear;echo $'\n'$"Exiting XBT... Goodbye $USER!";sleep 2;tput cnorm;exit;;
            *) echo "Not a valid choice: Please try again.";sleep 2;clear;greeting;;

	esac

}

help() {

    # Print help information using less utility:

	clear
    less << _EOF_

 XBT -- External Backup Tool -- Help
 (v. 3.1) Updated to work for Debian OS's (Only!)

 Press "q" to exit this Help page and return to Main Menu.

 Commands:

 xbt = Starts XBT program with menu options.
 xbt --backup = Fully backs up host's /etc and /home directories to XBT_Drive.
 xbt --restore = Fully restores host machine's /home directory from XBT_Drive.
 xbt --help = Prints this help information.
 xbt --log = Prints log from XBT drive in interactive viewer. ("q" to exit.)

 Description:

 (--- XBT has been updated so that it will work for Debian
 OS's & APT package manager.---)

 XBT is a program that makes keeping all of your user data safely backed up on
 a dedicated External USB drive easy.

 XBT will update files that have changed, remove files that have been
 deleted and add any new files that have been created since the last backup.
 The initial backup can take a lot of time if you have a lot of data stored
 in your system's /home directory. XBT creates a directory with the host name
 of the machine it's backing up from inside XBT-Backups. This allows users to
 share one XBT_Drive with multiple machines.

 The directory structure and all files are stored openly to allow users easy
 access if they only need to retrieve a few files or directories using a file
 manager. Data from /home can be restored with the built in "xbt restore"
 command if the user wants to roll back to the exact state of /home when the
 last backup was taken.

 A simple log file is added to the XBT_Drive that shows when each new
 backup is taken and any errors that might occur. This file is appended
 every time XBT is run. The log file is placed in XBT-Backups. You can view the
 last several backups by using the XBT Log viewer. Press "q" to exit when
 you're done.

 Requirements:

 Note: *****
 This XBT has been updated and tested so that it will work on
 Debian OS's APT package manager.

 This XBT was designed to work Linux Ubuntu type Distro's.
 You need to prepare an XBT Drive.
 This can be any USB storage device. The dedicated USB drive must be
 formatted to a Linux native file system such as Ext4 to ensure that file
 permissions will be stored unchanged. The USB drive needs to have enough
 free capacity to store all data in /home on all of the machines you want to
 use the drive for. The drive MUST be labeled as "XBT_Drive" for the script
 to run. If XBT_Drive is not detected, the script exits with an error.

 XBT Drive Setup allows you to choose a drive to designate as the XBT Drive.
 The selected drive will be "blanked," formatted with ext4 and labeled
 'XBT_Drive." This option is available in the Main Menu.

 Feedback:

 Feel free to contact EzeeLinux with comments and suggestions for XBT and
 future projects.

  www.ezeelinux.com

 Enjoy using XBT!

 - Joe Collins

   December, 2017

 *************************************************************
 I updated this great project to function for "Solus 4.0"
 Update comments.. Contact - Bruce E. Scott
 at - "bescott9944@gmail.com"   April, 2019
 *************************************************************
 Date: 5/21/2019 (V. 3.0.2) Update ---- Bruce E. Scott

 Hello,
 I ported Joe's great XBT backup tool so that it will work
 on Solus Budgie 4.0 and the EOPKG package manager as
 well as Ubuntu Distro's...

 This tool still in accordance with (GNU/General Public License version 2.0)
 and all changes were made by me (Bruce E. Scott) on 5/12/2019...

 This should work with any Distro that uses the EOPKG manager!
 It has been tested on Solus 4.0 "Fortitude" ONLY and works so far!!

 Note: when lanching XBT there is a 6 seconds delay while EOPKG checks for
 Less, Parted, Rsync to see if there installed. If not, they will be
 installed and you will be asked for your SuDo passward to install them!

 Use this adapted Solus & Manjaro Arch software at your own RISK!!! You have
 been warned! - Bruce E. Scott
  *************************************************************
 Date:  6/5/19 (V. 3.0.3) Update ---- Bruce E. Scott

  		"CYA Backup Solution Added"
  	"Cya, Copyright (c) 2017, Jeremy O'Connell"
 Hello,
 I added Jeremy O'Connell "CYA Backup Solution" to the Function & Menu areas
 so that it can be ran from inside XBT-Solus.
 The command line function for CYA is set to "CYA Save"... Any other commands
 options will need to be done from a "Terminal Command Line"

 I add this to make the backup prossess easier to do from one "Menu"
 Bruce E. Scott...
  *************************************************************
 I updated this script to now work on Manjaro Arch and the PACMAN package manager
 on 07/03/19 -Bruce
 *************************************************************
 I updated this script to now work on Manjaro Arch and the PACMAN package manager
 on 07/03/19 -Bruce
 *************************************************************
 Date:  01/18/2020 (V. 3.1) Update ---- Bruce E. Scott
 I updated V3.0 to work for Debian OS's with the APT Package Manager.
 I updated this script to now work with differant switches and
 "excluding" items. They are:
     sudo rsync -aAHXv --delete --progress --exclude=/tmp/*
    --exclude=**/*tmp*/ --exclude=/run/** --exclude=/mnt/**
    --exclude=/media/*/** --exclude=swapfile --exclude=**/lost+found*/
    --exclude=/bruce/.cache/ --exclude=**/*cache*/
    --exclude=**/*Cache*/ --exclude=/var/run/** --exclude=**/*Trash*/
    --exclude=**/*trash*/ --exclude=/bruce/Music/ServerMusic/**
    --exclude=/bruce/Documents/Master-Docs/** --exclude=/timeshift/**
    --exclude=/bruce/Videos/** --exclude=/cya/**
 to keep them from being back-up to the XBT drive. They do not need to
 be back-uped. This is done on the server...
 Also a verson update to V 3.1... 01/18/2020
  *************************************************************

 Disclaimer:

 THIS SOFTWARE IS PROVIDED BY EZEELINUX “AS IS” AND ANY EXPRESS OR IMPLIED
 WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 EVENT SHALL EZEELINUX BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.

_EOF_

# Exit if running from command line:

if [ "$mode" == "CLI" ]; then
	exit
fi

clear
greeting

}

log() {

# XBT Log Viewer. Shows the log file with less.

# Check for valid media and log file:

if [ ! -f /media/$user/XBT_Drive/XBT_Backups/xbt-backup.log ]; then

    # Check for log file and return to Main Menu with error if not found:

    clear
    echo $'\n'$"XBT Log Viewer"
    echo "XBT Error: No log file found. Make sure XBT_Drive USB is connected."
    echo "Note: The log is generated during the first XBT Backup."
    greeting

fi

# Load log file into less:
# "less +G" opens file and scrolls to end."

less +G /media/$user/XBT_Drive/XBT_Backups/xbt-backup.log
clear

# Exit if running from command line:

if [ "$mode" == "CLI" ]; then
	exit
fi

greeting

}

# Execution Section

# Checking for command line arguments:

if [ "$1" == "--help" ]; then
	mode=CLI
	help
fi

if [ "$1" == "--log" ]; then
	mode=CLI
	log
fi

if [ "$1" == "--backup" ]; then
	mode=CLI
	backup
fi

if [ "$1" == "--restore" ]; then
	mode=CLI
	restore
fi

if  [ -n "$1"  ]; then
    echo "XBT Error: Invalid argument. Exiting to Main Menu."
    sleep 3
fi

if [ "$1" == "--before" ]; then
	mode=CLI
	before
fi

if [ "$1" == "--cya" ]; then
	mode=CLI
	cya
fi


if [ "$1" == "--after" ]; then
	mode=CLI
	after
    greeting
fi


clear
echo "  Greetings and Salutations $USER! You are using $HOSTNAME..."

greeting
