#!/bin/bash

# Script to automatically change the wallpaper and lock screen in spectrwm

# Directory Containing the Pictures

# DIR="/home/$USER/Pictures/Wallpapers"
# DIR="/home/bruce/Pictures/Wallpapers/DTs-Wallpapers"
DIR="/home/$USER/Pictures/Wallpapers/EndeavourOS"
# DIR="/home/$USER/Pictures/Wallpapers/black-wallpapers"
# EndeavourOS"

# Command to Select wallpapers at random from the $DIR directory

# WAL=$(ls $DIR/*.png | shuf -n1)
WAL=$(ls $DIR/*.* | shuf -n1)

# Set lockscreen wallpaper

cat $WAL > /home/$USER/Pictures/Wallok/wallok.jpg

# Set Desktop Wallpaper

# feh --bg-scale /home/$USER/Pictures/Wallok/wallok.jpg
feh --bg-center /home/$USER/Pictures/Wallok/wallok.jpg
