#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set screen resolution before leftwm theme gets loaded
# /home/bruce/.screenlayout/leftwm.sh 

#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null & 
fi

# Loading Xrandr to set the screen resolution from a Arnadr script
# /home/bruce/.screenlayout/spectrwm.sh 

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#set startup apps
#/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
nitrogen --restore
# &
setxkbmap -layout US
# ###xinput set-prop "Synaptics TM3157-004" "libinput Tapping Enabled" 1

# Conky - Starting my conkys
# ~/.conky/start-conky.sh
/home/bruce/.config/leftwm/start-conky-term.sh
# start-conky-term.sh

index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do 
  barname="mainbar$index"
  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=index+1
done

